---
grails:
    profile: rest-api
    codegen:
        defaultPackage: bursapp
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    config:
        locations:
            - ApiCallsJsonConfig.groovy
            - Config.groovy
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
        domain:
            include:
                class: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
            username: sa
            password: ''
            url: jdbc:mysql://localhost:3306/bursapp
            properties :
                maxActive : 50
                maxIdle : 25
                minIdle : 1
                initialSize : 1

                numTestsPerEvictionRun : 3
                maxWait : 10000

                testOnBorrow : true
                testWhileIdle : true
                testOnReturn : true

                validationQuery : "select now()"

                minEvictableIdleTimeMillis : 1000 * 60 * 5
                timeBetweenEvictionRunsMillis : 1000 * 60 * 5

    test:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
            username: sa
            password: ''
            url: jdbc:mysql://localhost:3306/bursapp
            properties :
                maxActive : 50
                maxIdle : 25
                minIdle : 1
                initialSize : 1

                numTestsPerEvictionRun : 3
                maxWait : 10000

                testOnBorrow : true
                testWhileIdle : true
                testOnReturn : true

                validationQuery : "select now()"

                minEvictableIdleTimeMillis : 1000 * 60 * 5
                timeBetweenEvictionRunsMillis : 1000 * 60 * 5
    production:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: 'root'
            url: jdbc:mysql://localhost:3306/bursapp
            properties :
                maxActive : 50
                maxIdle : 25
                minIdle : 1
                initialSize : 1

                numTestsPerEvictionRun : 3
                maxWait : 10000

                testOnBorrow : true
                testWhileIdle : true
                testOnReturn : true

                validationQuery : "select now()"

                minEvictableIdleTimeMillis : 1000 * 60 * 5
                timeBetweenEvictionRunsMillis : 1000 * 60 * 5